### ISSUE TITLE
py3 compatibility commit broke py2 compatibility

### ISSUE THREAD

**Issue by veritazx** [collective/Products.BeakerSessionDataManager#13]
The BeakerSessionDataObject class still needs to inherit UserDict for the methods to work.

Puttin a key/value pair into the session via set produced:
Module Products.BeakerSessionDataManager.sessiondata, line 148, in mutating_func
TypeError: unbound method setitem() must be called with UserDict instance as first argument (got BeakerSessionDataObject instance instead)

**Comment by davisagli** [comment]
Support for Python 2 was removed in the 2.0 release. Use version 1.1 on Python 2.

**Comment by veritazx** [comment]
Hm. There is only mention of dropped python 2.6 support. I assumed, 2.7 was still supported. But I found a PR for my problem, that I overlooked before. So the issue can stay closed. I'll remove the branches as soon as we have checked that the PR really fixes our problems. 1.1 is not a valid solution for us anymore, we need newer Beaker versions.
